accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .views import (
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView,
)

app_name ='accounts'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('dashboard', views.dashboard, name='dashboard'),
     # Minimal password reset URLs
    path('password-reset/', 
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html',
             email_template_name='accounts/password_reset_email.html',
             success_url='done/'
         ), 
         name='password_reset'),
    
    path('password-reset/done/', 
         auth_views.PasswordResetDoneView.as_view(
             template_name='accounts/password_reset_done.html'
         ), 
         name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/', 
         auth_views.PasswordResetConfirmView.as_view(
             template_name='accounts/password_reset_confirm.html',
             success_url='/accounts/reset/done/'
         ), 
         name='password_reset_confirm'),
    
    path('reset/done/', 
         auth_views.PasswordResetCompleteView.as_view(
             template_name='accounts/password_reset_complete.html'
         ), 
         name='password_reset_complete'),
]

careers/urls.py
from django.urls import path
from . import views

app_name = 'careers'

urlpatterns = [
    path('', views.career_list, name='list'),
    path('<int:job_id>/', views.career_detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from debug_toolbar.toolbar import debug_toolbar_urls 

urlpatterns = [
    path('', include ('pages.urls',namespace='pages')),
    path('listings/', include ('listings.urls',namespace='listings')),
    path('contacts/', include ('contacts.urls',namespace='contacts')),
    path('accounts/', include ('accounts.urls',namespace='accounts')),
    path('mortgages/', include('mortgages.urls',namespace='mortgages')),
    path('careers/', include('careers.urls')),
    path('news/', include('news.urls')),  # Add this line
    path('admin/', admin.site.urls),
    
    
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()

admin.site.site_header = "Property Adminstration"
admin.site.site_title = "Property Admin Portal"
admin.site.index_title = "Welcome to Property Portal"

mortgages/urls.py
from django.urls import path
from . import views
from .views import mortgage_calculator

app_name='mortgages'
urlpatterns = [
    path('', mortgage_calculator, name='calculator'),
]

news/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.news_list, name='news_list'),
   
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

templates/partials/_alert.html
{% if messages %}
{% for message in messages %}
<div class="container" id="message">
    <div 
    class="alert alert-dismissible text-center alert-{{ message.tags }}" role="alert">

    <button class="close" type="button" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
    </button>
    <strong>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} Error: {% else %}
        {{message.tags | title }} {% endif %}</strong
        >{{message}}

    </div>
</div>



{% endfor %}
{% endif %}

templates/partials/_footer.html
    <!-- Footer -->
    <footer id="main-footer" class="py-4 bg-primary text-white text-center">
      Copyright &copy;
      <span class="year"></span> UrbanNest Property
    </footer>
    

templates/partials/_navbar.html
{% load static %}
<head>
<!-- Navbar -->
    {% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top"> {% endcomment %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
      <div class="container">
        <a class="navbar-brand" href={% url 'pages:index' %}>
          <img src= {% static 'img/logo.png' %} class="logo" alt="" />
        </a> 
            {% comment %} <div class="hero-icon text-white mr-4">
                  <h1 class="fas fa-home"></h1>
                  {% comment %} <h1 class=" fas fa-home fa-5x"></h1>
            </div> {% endcomment %}
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
          
          <li {% if '/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
            <a class="nav-link" href={% url 'pages:index' %}><strong>Home</strong></a>
          </li>
      
            <li {% if '/listings/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}> 
            <a class="nav-link" href={% url 'listings:index' %}>
              <strong>Our Properties</strong>
            </a>
            </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <strong>Others Services</strong>
            </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href={% url 'mortgages:calculator' %}><strong>Mortgage Calculator</strong></a>
          <a class="dropdown-item" href={% url 'careers:list' %}><strong>Job Opening</strong></a>
          <a class="dropdown-item" href={% url 'news_list' %}><strong>Property News</strong></a>
        </div>
      </li>
    </li>
            <li {% if '/about' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                
                <a class="nav-link mr-3" href={% url 'pages:about' %}><strong>About</strong></a>
            </li>

    </ul>
        


          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li {% if 'dashboard' in request.path %} class="nav-item mr-3 active" {% else %} class="nav-item mr-3" {% endif %}>
                <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                <i class="fas fa-user-plus"></i> Welcome {{ user.username }}(dashboard)</a
              >
            </li>
            <!--logout-->
            <li class="nav-item mr-3">
              <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                <i class="fas fa-sign-out-alt"></i>Logout
              </a>
            <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
              {% csrf_token %}
              <input type="hidden"/>
            </form>
            </li>
            {% else %}
            <li {% if 'register' in request.path %} class="nav-item mr-3 active" {% else %} class="nav-item mr-3" {% endif %}>
                <a class="nav-link" href="{% url 'accounts:register' %}">
                <i class="fas fa-user-plus"></i> <strong>Register</strong></a
              >
            </li>
            <li {% if 'login' in request.path %} class="nav-item mr-3 active" {% else %} class="nav-item mr-3" {% endif %}>
                <a class="nav-link" href="{% url 'accounts:login' %}">
                <i class="fas fa-sign-in-alt"></i>

                <strong>Login</strong></a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
  </head>

templates/partials/_navbar2.html
{% load static %}
<!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
      <div class="container">
        <a class="navbar-brand" href={% url 'pages:index' %}>
          <img src= {% static 'img/logo.png' %} class="logo" alt="" />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <ul class="navbar-nav">
            <li {% if '/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>

                
                <a class="nav-link" href={% url 'pages:index' %}>Home</a>
            </li>
            <li {% if '/about' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}>
                
                <a class="nav-link" href={% url 'pages:about' %}>About</a>
            </li>
            <li {% if '/listings/' == request.path %} class="nav-item active mr-3" {% else %} class="nav-item mr-3" {% endif %}> 
                <a class="nav-link" href={% url 'listings:index' %}>
                  Property services
                </a>
            </li>
          </ul>

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li {% if 'dashboard' in request.path %} class="nav-item mr-3 active" {% else %} class="nav-item mr-3" {% endif %}>
                <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                <i class="fas fa-user-plus"></i> Welcome {{ user.username }}(dashboard)</a
              >
            </li>
            <!--logout-->
            <li class="nav-item mr-3">
              <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                <i class="fas fa-sign-out-alt"></i>Logout
              </a>
    <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
      {% csrf_token %}
      <input type="hidden"/>
    </form>
            </li>
            {% else %}
            <li {% if 'register' in request.path %} class="nav-item mr-3 active" {% else %} class="nav-item mr-3" {% endif %}>
                <a class="nav-link" href="{% url 'accounts:register' %}">
                <i class="fas fa-user-plus"></i> Register</a
              >
            </li>
            <li {% if 'login' in request.path %} class="nav-item mr-3 active" {% else %} class="nav-item mr-3" {% endif %}>
                <a class="nav-link" href="{% url 'accounts:login' %}">
                <i class="fas fa-sign-in-alt"></i>

                Login</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

templates/partials/_topbar.html
<!-- Top Bar -->
    <section id="top-bar" class="p-3">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <i class="fas fa-phone"></i> (852)-8888-8888
          </div>
          <div class="col-md-4">
            <i class="fas fa-envelope-open"></i> contact@urbannest.co
          </div>
          <div class="col-md-4">
            <div class="social text-right">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
              <a href="#">
                <i class="fab fa-facebook"></i>
              </a>
              <a href="#">
                <i class="fab fa-linkedin"></i>
              </a>
              <a href="#">
                <i class="fab fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fab fa-pinterest"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>